# Generated by Django 5.1.4 on 2024-12-28 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullName', models.CharField(max_length=255)),
                ('avatar', models.URLField()),
                ('coverImage', models.URLField()),
                ('password', models.TextField()),
                ('refreshToken', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('videoFile', models.URLField()),
                ('thumbnail', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('views', models.IntegerField()),
                ('isPublished', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_owner', to='api.users')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='watchHistory',
            field=models.ManyToManyField(blank=True, related_name='video_viewed_by', to='api.videos'),
        ),
    ]
